import csv
from collections import Counter

# Well-known artists to KEEP
known = {
    # User explicitly requested dark wave/EBM:
    'Faderhead', 'Sisters of Mercy', 'Front 242', 'VNV Nation', 'CHROM', 'The Neon Judgement',
    # Major Synthpop/New Wave
    'Depeche Mode', 'New Order', 'The Cure', 'Orchestral Manoeuvres In The Dark',
    'Tears For Fears', 'Erasure', 'Ultravox', 'A Flock Of Seagulls', 'Joy Division',
    'The Human League', 'Duran Duran', 'Eurythmics;Annie Lennox;Dave Stewart',
    'Spandau Ballet', 'ABC', 'Thompson Twins', 'Howard Jones', 'Pet Shop Boys',
    'Culture Club', 'Soft Cell', 'Talk Talk', 'Frankie Goes To Hollywood',
    'Gary Numan', 'The Psychedelic Furs', 'Roxy Music', 'Simple Minds',
    'Modern Talking', 'The Police', 'Yazoo', "The B-52's", 'Blondie',
    'Alphaville', 'Modern English', 'Thomas Dolby', 'Missing Persons',
    'Mr. Mister', 'a-ha', 'Go West', 'Kim Wilde', 'Heaven 17',
    'Camouflage', 'Visage', 'Dead Or Alive', 'Information Society',
    'Naked Eyes', 'Berlin', 'Japan', 'The Communards', 'Bronski Beat',
    'Fine Young Cannibals', 'Madness', "The Go-Go's", 'DEVO',
    'Nik Kershaw', 'China Crisis', 'Johnny Hates Jazz',
    'Altered Images', 'Everything But The Girl', 'Blancmange',
    'Siouxsie and the Banshees', 'Echo & the Bunnymen', 'The Smiths',
    'Talking Heads', 'The Cars', 'The Stranglers', 'The Jam',
    'Haircut 100', 'Swing Out Sister', 'Bryan Ferry',
    'The The', 'When In Rome', 'Real Life', 'Starship',
    'Peter Schilling', 'Bananarama', 'Men At Work',
    'Prefab Sprout', 'Aztec Camera', 'The Style Council',
    'Level 42', 'Wang Chung', 'The Fixx',
    'Re-Flex', 'Trans-X', 'Limahl', 'Nena',
    'Red Flag', 'Anything Box', 'Book Of Love',
    'The Motels', 'The Romantics',
    'Prefab Sprout;Thomas Dolby', 'Japan;Steve Nye',
    'The Communards;Sarah Jane Morris',
    "'Til Tuesday",
    # Pop/Rock Legends
    'Queen', 'Michael Jackson', 'Madonna', 'The Beatles', 'The Rolling Stones',
    'David Bowie', 'Prince', 'Elton John', 'Phil Collins', 'Genesis',
    'Rod Stewart', 'Billy Joel', 'Bruce Springsteen', 'Daryl Hall & John Oates',
    'Fleetwood Mac', 'Whitney Houston', 'TOTO', 'Dire Straits',
    'Billy Idol', 'Steve Winwood', 'George Michael', 'U2',
    'Roxette', 'Sandra', 'ABBA', 'Bryan Adams', 'Chris de Burgh',
    'Kylie Minogue', 'Simply Red', 'Bee Gees', 'Stevie Wonder',
    'Tina Turner', 'Lionel Richie', 'Paul Young', 'Wham!',
    'Billy Ocean', 'Pat Benatar', 'Alison Moyet', 'Cyndi Lauper',
    'Robert Palmer', 'Rick Astley', 'Robbie Williams', 'Seal',
    'Suzanne Vega', 'Jennifer Rush', 'Laura Branigan', 'Stevie Nicks',
    'Mariah Carey', 'Taylor Dayne',
    'Rick Springfield', 'John Waite', 'Peter Cetera',
    'Feargal Sharkey', 'Adam Ant', 'Joe Jackson',
    'Falco', 'Peter Gabriel', 'Paul McCartney',
    'Cliff Richard', 'Roy Orbison', 'Crowded House',
    'Sting', 'Chris Rea', 'Mark Knopfler',
    'Belinda Carlisle', 'Paula Abdul', 'Tiffany', 'Debbie Gibson',
    'Jason Donovan;Kylie Minogue', 'Robin Beck',
    'New Kids On The Block', 'Neneh Cherry',
    'Wet Wet Wet', 'UB40', 'Bros',
    'Samantha Fox', 'Sabrina', 'Sonia',
    'Transvision Vamp', 'Adamski;Seal',
    # Collabs
    'Elton John;Kiki Dee', 'Elton John;Dua Lipa;PNAU',
    'Lionel Richie;Diana Ross', 'Philip Bailey;Phil Collins',
    'Bill Medley;Jennifer Warnes', 'Patrick Swayze;Wendy Fraser',
    'The Bangles;Susanna Hoffs', 'Miami Sound Machine;Gloria Estefan',
    'Eurythmics;Annie Lennox;Dave Stewart;Aretha Franklin',
    'Pet Shop Boys;Dusty Springfield',
    'Lisa Stansfield;Ian Devaney;Andy Morris',
    'Soul II Soul;Caron Wheeler', 'Roxette;Peter Bostr\u00f6m',
    "Robert Palmer;Eric 'ET' Thorngren",
    'Tom Jones;Mousse T.',
    'Purple Disco Machine;Sophie and the Giants',
    'Run\u2013D.M.C.;Aerosmith',
    'Tears For Fears;Dave Bascombe', 'Tears For Fears;Oleta Adams',
    'Phil Oakey;Giorgio Moroder', 'Philip Oakey;Giorgio Moroder',
    # Disco/Funk/Soul
    'Donna Summer', 'Boney M.', 'Gibson Brothers', 'CHIC',
    'The Pointer Sisters', 'Earth, Wind & Fire', 'Sister Sledge',
    'Kool & The Gang', 'KC & The Sunshine Band', 'Gloria Gaynor',
    'Dan Hartman', 'Patrick Hernandez', 'Bobby Brown',
    'James Brown', 'Marvin Gaye', 'The Jacksons',
    'Chaka Khan', 'Shalamar', 'Cameo',
    'Lipps Inc.', 'Ottawan', 'Imagination',
    'Odyssey', 'Leo Sayer', 'Inner City',
    'Evelyn "Champagne" King',
    # Hard Rock / Metal
    'AC/DC', 'Metallica', 'Aerosmith', 'Foreigner', 'Def Leppard',
    'ZZ Top', 'Van Halen', 'Bon Jovi', "Guns N' Roses", 'KISS',
    'Scorpions', 'Whitesnake', 'Europe', 'Heart', 'Journey', 'Survivor',
    'Iron Maiden', 'Judas Priest', 'Ozzy Osbourne', 'Led Zeppelin',
    'Poison', 'Cinderella', 'Skid Row',
    'Cheap Trick', 'REO Speedwagon', 'Loverboy', 'Steve Miller Band',
    'Bob Seger', 'Don Henley', 'Tom Petty', 'Tom Petty and the Heartbreakers',
    'Bruce Hornsby and the Range', 'Huey Lewis & The News',
    'Styx', 'Chicago', 'Supertramp', 'Status Quo',
    'Gary Moore', 'Quiet Riot', 'W.A.S.P.',
    'Eddie Money', 'John Mellencamp', '38 Special',
    'Mick Jagger',
    # Classic Rock
    'Pink Floyd', 'The Who', 'Creedence Clearwater Revival', 'The Doors',
    'Jimi Hendrix', 'Eagles', 'Eric Clapton', 'Santana',
    'Electric Light Orchestra', 'Thin Lizzy', 'Allman Brothers Band',
    'Lynyrd Skynyrd', 'Simon & Garfunkel', 'The Doobie Brothers',
    'Ramones', 'Sex Pistols', 'The Clash', 'T. Rex',
    'Rush', 'Rainbow', 'Janis Joplin', 'Canned Heat',
    'Traveling Wilburys', "Manfred Mann's Earth Band",
    'Barclay James Harvest', 'Smokie',
    'Mike + The Mechanics', 'Sparks', 'Donald Fagen',
    # 90s/2000s Rock
    'Nirvana', 'Pearl Jam', 'Green Day', 'Red Hot Chili Peppers',
    'R.E.M.', 'Oasis', 'Linkin Park', 'Foo Fighters',
    'The Cranberries', 'The Offspring', 'Alice In Chains',
    'Beastie Boys', 'The Verve', 'Nickelback',
    'System Of A Down', '3 Doors Down', 'Kings of Leon',
    'Matchbox Twenty', 'blink-182', 'Billy Talent',
    'Counting Crows', 'Silverchair', 'Savage Garden',
    'Creed', 'The Cardigans', 'Ugly Kid Joe', 'CAKE',
    'Gin Blossoms', 'Del Amitri', 'Jeff Buckley',
    'A Tribe Called Quest', 'Cypress Hill',
    'Fugees;Ms. Lauryn Hill;Wyclef Jean;Pras', 'Ms. Lauryn Hill',
    # 90s/2000s Pop/RnB
    "Destiny's Child", 'TLC', '*NSYNC', 'Christina Aguilera',
    'Justin Timberlake', 'Milli Vanilli', 'Salt-N-Pepa',
    'Jennifer Paige', 't.A.T.u.',
    # Electronic/Synth
    'Kraftwerk', 'Mike Oldfield', 'Yello', 'Enigma',
    'The Alan Parsons Project', 'Jean-Michel Jarre', 'Vangelis',
    'Jan Hammer', 'Tangerine Dream', 'Giorgio Moroder',
    'The Art Of Noise', 'Harold Faltermeyer', 'Schiller',
    'Kitaro', 'Jon & Vangelis', 'Faithless', 'Moby',
    'The Prodigy', 'Daft Punk', 'Enya',
    'Ennio Morricone',
    # Eurodance/Dance
    '2 Unlimited', 'Scooter', 'Real McCoy', 'La Bouche',
    'DJ BoBo', 'Aqua', 'Vengaboys', 'Haddaway',
    'Dr. Alban', 'Robert Miles', 'ATB', 'Darude', 'Jamiroquai',
    'Eiffel 65;Gabry Ponte', 'Alice Deejay', 'Sash!',
    'Technotronic;Felly', 'C & C Music Factory;Freedom Williams',
    "GIGI D'AGOSTINO", 'Paul Elstak', 'Deee-Lite',
    'U96', 'Dune', 'Marusha',
    # Rammstein
    'Rammstein',
    # Dark Wave/Industrial/Post-Punk
    'Bauhaus', 'DAF', 'Nitzer Ebb', 'Ministry',
    'Killing Joke', 'Fad Gadget', 'The Mission',
    'Anne Clark', 'Propaganda', 'Clan of Xymox',
    'Wolfsheim', 'Project Pitchfork', 'Diary Of Dreams',
    'Deine Lakaien', 'De/Vision', 'Covenant', 'Blutengel',
    'She Past Away', 'Peter Murphy', 'Love and Rockets',
    'Public Image Ltd.', 'Gang Of Four',
    'Xmal Deutschland', 'Cabaret Voltaire',
    'The Jesus and Mary Chain', 'Pixies',
    'Martha and the Muffins', 'The Cult',
    'The Boomtown Rats', 'Bob Geldof',
    # German
    'Die Fantastischen Vier', 'Udo Lindenberg', 'Peter Maffay',
    'Matthias Reim', 'Hubert Kah', 'C.C. Catch',
    'Bad Boys Blue', 'Blue System',
    # Various well-known
    'Big Country', 'Pretenders', 'Kate Bush', 'Marillion',
    'ICEHOUSE', 'The Outfield', 'Fra Lippo Lippi',
    'Cutting Crew', 'Fischer-Z', 'The Hooters',
    'Richard Marx', 'Christopher Cross', 'Air Supply',
    'Oingo Boingo', 'Kenny Loggins',
    'Sade', 'Miami Sound Machine',
    'Deacon Blue',
    'Frank Stallone', 'Murray Head', 'F.R. David',
    'John Parr', 'Midnight Oil', 'Animotion',
    'Flash and the Pan', 'General Public',
    'Bow Wow Wow', 'Toni Basil', 'The Church', 'Split Enz',
    'Men Without Hats', 'Double',
    'Tone-Loc', 'Whigfield',
    'Sananda Maitreya',
    'Modjo', 'George Benson', 'Cheryl Lynn',
    'Robin Gibb', 'Patti LaBelle;LaBelle',
    'Anita Ward', 'Patrice Rushen',
    'Black Lace', 'Jive Bunny and the Mastermixers',
    'Goombay Dance Band', 'Eruption',
    'Jason Mraz',
    'Dario G', 'Robert Plant',
    'iNi Kamoze;Salaam Remi',
    'Majestic;Boney M.',
    'Gary Numan;Tubeway Army', 'Tubeway Army',
    'Warrant', 'Great White', 'Firehouse', 'Winger',
    'Ted Nugent', 'UFO', 'Billy Squier',
    'Steve Perry',
    'M/A/R/R/S',
    'Groove Coverage',
    '2 Brothers On The 4th Floor',
    'Charly Lownoise & Mental Theo',
    'Solid Base', 'La Bionda',
    'Ice Mc', 'Magic Affair',
    'Brooklyn Bounce', 'New Limit',
    'Blumchen',
    'Party Animals;Flamman & Abraxas',
    'Da Buzz', 'French Affair', 'Apollo 440',
    'Mark "Oh"',
    'Interactive', 'Mr. President',
    'Party Animals', 'Leila K',
    'Future Breeze', 'Mauro Picotto',
    'Critical Mass',
    'RMB', 'Snap!',
    'Colonel Abrams', 'Womack & Womack', 'Aswad',
    'Jeffrey Osborne', 'Mel & Kim',
    'Luther Vandross',
    'The Commitments;Andrew Strong',
    'Jermaine Stewart',
    'Alexander O\'Neal;Steve Hodge',
    'Hue and Cry', 'Roachford',
    'The Housemartins',
    'Climie Fisher', 'The Waterboys', 'Danny Wilson',
    'S\'Express',
    'Yazz',
    "C\u00e9line Dion",
    'Daryl Braithwaite',
    'The Tubes',
    'Yngwie Malmsteen',
    'Joe "Bean" Esposito',
    'Jude Cole',
    'Benjamin Orr',
    'Gene Loves Jezebel',
    'M\u00f6tley Cr\u00fce',
    'Rheingold',
    'Ken Laszlo', 'Fancy',
    'Silent Circle', 'Ibo',
    'Black', 'Piano Fantasia',
    'Lime', 'Cerrone',
    'Patrick Hernandez;Herv\u00e9 Tholance',
    'Boytronic', 'Laserdance',
    'Patrick Cowley',
    'Moon Ray', 'Koto',
    'George Thorogood & The Destroyers',
    'TC Matic',
    'Snowy Red', 'Red Zebra',
    'Virgin Prunes', 'Kirlian Camera',
    'Vicious Pink', 'Shriekback',
    'A Split-Second',
    'De Brassers', 'Arbeid Adelt!', 'Executive Slacks',
    '2 Belgen', 'Lavvi Ebbel', 'The Scabs',
    'De Kreuners', 'Vive La F\u00eate',
    'Lebanon Hanover', 'The KVB', 'Molchat Doma',
    'Boy Harsher', 'Twin Tribes', 'Mr.Kitty',
    'Light Asylum',
    'The Bollock Brothers',
    'Nacht Und Nebel',
    'Joy', 'Valerie Dore', 'Miko Mission',
    'Breakfast Club',
    'The Wild Swans', 'The Lotus Eaters',
    'The Dream Academy', 'The Icicle Works',
    'The Colourfield', 'The Adventures',
    'Belouis Some', 'The Associates',
    'Landscape', 'Aneka', 'King',
    'Al Corley', 'Flesh For Lulu', 'Kon Kan',
    'Eurogliders', 'The Sundays',
    'Jane Wiedlin', 'Generation X',
    'C.C.C.P.',
    'Industry',
    'Jo Boxers', 'Squeeze',
    'Vitamin Z', 'Fiction Factory',
    'Red Rockers', 'The Vapors',
    'M / Robin Scott',
    'Colors', 'Timmy Thomas',
    'The Mighty Lemon Drops',
    'Deniece Williams', 'Stephanie Mills',
    'Jon Secada',
    'Sheena Easton', 'The Flirtations',
    'Sybil', 'Alicia Bridges',
    'France Joli', 'Randy Crawford', 'Candi Staton',
    'Karen Young', 'A Taste Of Honey',
    'George Duke', 'Ashford & Simpson',
    'The Brothers Johnson', 'Gonzalez',
    'Joe Smooth', 'Viola Wills', 'Transamerica',
    'Evelyn Thomas',
    'Ray Conniff',
    'Real McCoy', 'Larusso',
    'Joachim Witt;Heppner', 'Donots',
    'Bob Sinclar;Gary Pine',
    'Peter Cetera', 'John Farnham',
    'Paradisio',
    'The Real Thing',
    'Night School', 'Delight',
    'The Whispers',
    'Rendez Vous',
    'Mike Francis;Rossana Casale', 'Mike Francis;Amii Stewart',
    'Rita Lee;Roberto De Carvalho',
    'Robyn;Christian "Falcon" Falk',
    'Magazine 60', 'Voyage', 'Kazero',
    'Tom Cavallaro',
    'The Jammin Kid;Majestic;C\u00e9line Dion',
    'Gala;Molella;Phil Jay',
    'Gibson Brothers;New Generation',
    'Patrick Hernandez;Snight B',
    'Sacha Distel',
    'Brooks;F.R. David',
    'Eddy Rosemond', 'Ronay', 'Ann C. Sheridan',
    'Chemise', 'Bibi Flash', 'Oliver Cheatham',
    'Wamdue Project;Roy Malone', 'Crazy Town', 'Electra',
    '4 The Cause', 'Lollies;KIZ',
    'Mandy & Randy', 'Andreas Martin',
    'Daze', 'Ginuwine',
    'EchoStorms;Selina Baron',
    'Sad Lovers & Giants', 'Parade Ground',
    'Klaus Schulze', 'Yanni',
    'Ed Starink', 'Serra',
    'Futureworld Orchestra',
    'The House of Love',
    'Luna Twist',
    'John Maus', 'Buzz Kull', 'Yaz',
    'Toad The Wet Sprocket',
    'Massive Ego', 'ES23', 'Eisfabrik',
    'Airbourne', 'Manowar',
    'Panther Modern', 'Madeline Goldstein',
    'My Manifesto',
    'America;George Martin',
    'Balu Brigada',
    'Slaughter',
    'Alain Morisod', 'Moroder', 'Sergio Presto',
    'Hammer', 'Jarre',
    'London Starlight Orchestra', 'Laura Bryna',
    'Frankie Muriel', 'In Denial 98',
    'R3SPAWN', 'Oh Well', 'AVAO', 'Zynic',
    'Rip Gerber', 'Addict.',
    'Cold Room Society', 'Matt Deangelis',
    'Box Chevy', 'Sparkle Blood',
    'Same Eyes',
    'Lou Sern', 'DJ In The Night', 'Angelina Lopez',
    'Electric Avenue',
    'Alain Turban', 'Roots', 'Quenzo',
    'Black White And Co', 'Fun Fun',
    'Enzo Pianzola Mr. Trend', 'Black Bells Group', 'Schooljay',
    'Francis Lai',
    'Stacey Q',
    'linequat;Pherick',
    'Mark Anthony Burke', 'The Good Hard',
    'mama no likey;Abrielle',
    'Ulrich Forman',
    'December Avenue', 'Jensen & The Flips',
    'Tom Tom Club',
    'Dr. Motte & WestBam present',
    'Raver\'s Nature', 'Intrance;Dsign',
    'Modern Talking;Eric Singleton',
    'Don Johnson',
    'Bonnie Tyler',
    'mgk;Fred Durst',
    'INXS',
    '10cc', 'Adam & The Ants', 'Alice Cooper',
    'Aretha Franklin;George Michael', 'Barry Manilow', 'Barry White',
    'Britney Spears', 'Coolio;L.V.', 'Diana Ross',
    'Eminem', 'Eurythmics', 'Extreme',
    'Faith No More', 'Fatboy Slim', 'George Harrison',
    'Gloria Estefan;Miami Sound Machine', 'Iggy Pop',
    'Janet Jackson', 'Joan Jett & the Blackhearts',
    'John Lennon', 'Lenny Kravitz', 'Morrissey',
    'Patti Smith', 'Radiohead', 'Vanilla Ice',
    'Will Smith', 'Will Smith;Dru Hill;Kool Moe Dee',
    'Youssou N\'Dour;Neneh Cherry', 'Zucchero;Paul Young',
    'N-Trance;Ricardo Da Force', 'N-Trance;Rod Stewart',
    'Dr. Dre;Snoop Dogg',
    'Bl\u00fcmchen',
    "Mark 'Oh",
    'Ti\u00ebsto',
    'The Sound',
    'SRNDE;one more cig',
    'SRNDE;Kin Alura',
}

# Filter CSV
with open('Playlists/My Hitster Playlist.csv', encoding='utf-8-sig', newline='') as f:
    reader = csv.DictReader(f)
    fieldnames = reader.fieldnames
    rows_keep = []
    rows_remove = []
    for row in reader:
        artist = row.get('Artist Name(s)', '').strip()
        if artist in known:
            rows_keep.append(row)
        else:
            rows_remove.append(row)

# Write new CSV
outfile = 'Playlists/My Hitster Playlist_Bekannt.csv'
with open(outfile, 'w', encoding='utf-8-sig', newline='') as f:
    writer = csv.DictWriter(f, fieldnames=fieldnames)
    writer.writeheader()
    writer.writerows(rows_keep)

# Stats
kept_artists = Counter(r.get('Artist Name(s)', '').strip() for r in rows_keep)
removed_artists = Counter(r.get('Artist Name(s)', '').strip() for r in rows_remove)

print(f'=== Neues CSV: {outfile} ===')
print(f'Behalten: {len(rows_keep)} Songs von {len(kept_artists)} Interpreten')
print(f'Nicht dabei: {len(rows_remove)} Songs von {len(removed_artists)} Interpreten')
print(f'\n--- Nicht aufgenommene Interpreten (2+ Songs) ---')
for a, c in removed_artists.most_common():
    if c >= 2:
        print(f'  {c:3d}x  {a}')
